/* PHRASES · seconde moitié
   Fichier GÉNÉRÉ par scripts/build-content.mjs. Ne pas éditer à la main.
   Aucune phrase n'a été inventée. Voir docs/V6_CONTENT.md.
   Statut linguistique : toutes les entrées sont "unverified".
   Le passage en "verified" est un geste humain, dans l'onglet
   Vérification, avec la source. */

export const PHRASES_B = [
 {
  "id": "lx085980c9",
  "lb": "heiansdo",
  "fr": "parfois",
  "ph": "haï-ans-do",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lxb140cfb8",
  "lb": "zesummen",
  "fr": "ensemble",
  "ph": "tse-zou-meune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx88fe7c3f",
  "lb": "Wat gëtt et Neies?",
  "fr": "quoi de neuf ?",
  "ph": "vat guétt ét naï-es",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-entendu",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx0c8d3ce2",
  "lb": "Ech ginn heem",
  "fr": "je rentre à la maison",
  "ph": "èkh guinn hém",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-entendu",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lxe57ca2f2",
  "lb": "Dat ass kloer",
  "fr": "c'est clair",
  "ph": "dat ass klou-er",
  "tr": "kloer, pense à clear.",
  "alt": [],
  "syl": 4,
  "paquet": "pk-entendu",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx32c69207",
  "lb": "Alles an der Rei",
  "fr": "tout est en ordre",
  "ph": "a-les an der raï",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-entendu",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lxe7274a99",
  "lb": "Maach et gutt",
  "fr": "porte-toi bien",
  "ph": "makh ét gout",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-entendu",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx3edd3b47",
  "lb": "Ech soen Iech Bescheed",
  "fr": "je vous tiens au courant",
  "ph": "èkh zo-eune i-eukh be-chét",
  "tr": "",
  "alt": [],
  "syl": 7,
  "paquet": "pk-entendu",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx3c881ec2",
  "lb": "d'Aarbecht",
  "fr": "le travail",
  "ph": "d'ar-bekht",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-travail",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx517f9ebe",
  "lb": "de Kolleeg",
  "fr": "le collègue",
  "ph": "de ko-lékh",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-travail",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx704df6d8",
  "lb": "de Chef",
  "fr": "le chef",
  "ph": "de chèf",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-travail",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx4b6c0cb3",
  "lb": "d'Equipe",
  "fr": "l'équipe",
  "ph": "d'é-kip",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-travail",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lxd5524d5f",
  "lb": "d'Sitzung",
  "fr": "la réunion",
  "ph": "d'zit-soung",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-travail",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx7d25c075",
  "lb": "Ech si prett",
  "fr": "je suis prêt",
  "ph": "èkh si prèt",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-travail",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx5d9375c7",
  "lb": "de Jong",
  "fr": "le garçon",
  "ph": "de yong",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jeunes",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lxf1578950",
  "lb": "d'Meedchen",
  "fr": "la fille",
  "ph": "d'méd-khen",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jeunes",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx952fba89",
  "lb": "de Jugendlechen",
  "fr": "l'adolescent",
  "ph": "de you-gend-le-khen",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-jeunes",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx4cd48d1c",
  "lb": "d'Schoul",
  "fr": "l'école",
  "ph": "d'choul",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-jeunes",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lx82248681",
  "lb": "d'Grupp",
  "fr": "le groupe",
  "ph": "d'group",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-jeunes",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "travail",
  "derive": false
 },
 {
  "id": "lxa354616d",
  "lb": "Ech si frou",
  "fr": "je suis content",
  "ph": "èkh si frou",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-emotions",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx9284f05e",
  "lb": "Ech si rosen",
  "fr": "je suis en colère",
  "ph": "èkh si ro-zeune",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-emotions",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxe6347558",
  "lb": "Ech hunn Angscht",
  "fr": "j'ai peur",
  "ph": "èkh hounn angcht",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-emotions",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx284f7b02",
  "lb": "Et geet net",
  "fr": "ça ne va pas",
  "ph": "ét guét nét",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-emotions",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxd179f9b2",
  "lb": "Ech si krank",
  "fr": "je suis malade",
  "ph": "èkh si krank",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-emotions",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxf5ac7b56",
  "lb": "Moien, hei ass …",
  "fr": "bonjour, ici c'est …",
  "ph": "mo-ï-eune haï ass",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-telephone",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "admin",
  "derive": false
 },
 {
  "id": "lxc704c234",
  "lb": "Ee Moment, wann ech gelift",
  "fr": "un instant, s'il vous plaît",
  "ph": "é mo-ment",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-telephone",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "admin",
  "derive": false
 },
 {
  "id": "lxbacabb1a",
  "lb": "Ech ruffen zréck",
  "fr": "je rappelle",
  "ph": "èkh rou-feune tsrék",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-telephone",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "admin",
  "derive": false
 },
 {
  "id": "lx9b68f182",
  "lb": "Ech hunn e Rendez-vous",
  "fr": "j'ai un rendez-vous",
  "ph": "èkh hounn e ran-dé-vou",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-telephone",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "admin",
  "derive": false
 },
 {
  "id": "lx67386338",
  "lb": "Kënnt Dir mir hëllefen?",
  "fr": "pouvez-vous m'aider ?",
  "ph": "kennt dir mir hè-le-feune",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-telephone",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "admin",
  "derive": false
 },
 {
  "id": "lx7b029843",
  "lb": "Merci a schéinen Dag",
  "fr": "merci et bonne journée",
  "ph": "mèr-si a chaï-neune dakh",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-telephone",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "admin",
  "derive": false
 },
 {
  "id": "lx2be88ca4",
  "lb": "null",
  "fr": "zéro",
  "ph": "noul",
  "tr": "null, comme nul. Zéro, c'est nul.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-1",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx3772901e",
  "lb": "eent",
  "fr": "un",
  "ph": "ént",
  "tr": "eent, une seule entité.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-1",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx4d0e3cbe",
  "lb": "zwee",
  "fr": "deux",
  "ph": "tsvé",
  "tr": "zwee finit par deux e collés.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-1",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxa4055e4a",
  "lb": "dräi",
  "fr": "trois",
  "ph": "draï",
  "tr": "dräi, les deux points du tréma plus le i, trois signes.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-1",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx0980347d",
  "lb": "véier",
  "fr": "quatre",
  "ph": "faï-er",
  "tr": "véier se dit faï-er, comme fire. Quatre bougies.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-1",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx1eb54b30",
  "lb": "fënnef",
  "fr": "cinq",
  "ph": "fè-neuf",
  "tr": "fënnef commence par F, comme five. Cinq doigts.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-1",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx4dea3e5f",
  "lb": "sechs",
  "fr": "six",
  "ph": "zeks",
  "tr": "sechs se dit zeks, six avec un z devant.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxebdf30c6",
  "lb": "siwen",
  "fr": "sept",
  "ph": "zi-veune",
  "tr": "siwen, pense à seven avec un z.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxdaa8097b",
  "lb": "aacht",
  "fr": "huit",
  "ph": "akht",
  "tr": "aacht, pense à eight. Le t final est dans les deux.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx5a40fe91",
  "lb": "néng",
  "fr": "neuf",
  "ph": "nèng",
  "tr": "néng, un n au début, comme neuf et nine.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxee2503dd",
  "lb": "zéng",
  "fr": "dix",
  "ph": "tsèng",
  "tr": "zéng, dix c'est zen.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx9c59399c",
  "lb": "eelef",
  "fr": "onze",
  "ph": "é-leuf",
  "tr": "eelef, pense à eleven.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx1a783da4",
  "lb": "zwielef",
  "fr": "douze",
  "ph": "tsvi-leuf",
  "tr": "zwielef commence comme zwee.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-2",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx56f9c389",
  "lb": "dräizéng",
  "fr": "treize",
  "ph": "draï-tsèng",
  "tr": "dräi plus zéng. Trois plus dix.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx51df26fb",
  "lb": "véierzéng",
  "fr": "quatorze",
  "ph": "faï-er-tsèng",
  "tr": "véier plus zéng.",
  "alt": [],
  "syl": 3,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx53b844de",
  "lb": "fofzéng",
  "fr": "quinze",
  "ph": "fof-tsèng",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx3bfd8b22",
  "lb": "siechzéng",
  "fr": "seize",
  "ph": "zi-eukh-tsèng",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxcfa86fa7",
  "lb": "siwwenzéng",
  "fr": "dix-sept",
  "ph": "zi-veune-tsèng",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx7dbc1ded",
  "lb": "uechtzéng",
  "fr": "dix-huit",
  "ph": "ou-eukht-tsèng",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx728f4cfb",
  "lb": "nonzéng",
  "fr": "dix-neuf",
  "ph": "non-tsèng",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx1eb7ca2f",
  "lb": "zwanzeg",
  "fr": "vingt",
  "ph": "tsvan-tsekh",
  "tr": "zwanzeg commence par zwee. Deux dizaines.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-3",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxfa094abd",
  "lb": "drësseg",
  "fr": "trente",
  "ph": "drè-sekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx1c0e7bfa",
  "lb": "véierzeg",
  "fr": "quarante",
  "ph": "faï-er-tsekh",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx2d54bfa5",
  "lb": "fofzeg",
  "fr": "cinquante",
  "ph": "fof-tsekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx4eca411e",
  "lb": "sechzeg",
  "fr": "soixante",
  "ph": "zek-tsekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxa9d7fd1d",
  "lb": "siwwenzeg",
  "fr": "soixante-dix",
  "ph": "zi-veune-tsekh",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx47877624",
  "lb": "achtzeg",
  "fr": "quatre-vingts",
  "ph": "akh-tsekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxfa3cc8d5",
  "lb": "nonzeg",
  "fr": "quatre-vingt-dix",
  "ph": "non-tsekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx361e3e8c",
  "lb": "honnert",
  "fr": "cent",
  "ph": "ho-nert",
  "tr": "honnert, pense à hundred.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxb223fc81",
  "lb": "dausend",
  "fr": "mille",
  "ph": "daou-zent",
  "tr": "dausend, pense à thousand.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-chiffres-4",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx8ee30f9c",
  "lb": "Lëtzebuerg",
  "fr": "le Luxembourg",
  "ph": "lét-se-bouerkh",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxa8911db4",
  "lb": "gëschter",
  "fr": "hier",
  "ph": "guèch-ter",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx5dab9888",
  "lb": "schéin",
  "fr": "beau",
  "ph": "chaïn",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx9bc09d51",
  "lb": "méi",
  "fr": "plus",
  "ph": "maï",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxad894f42",
  "lb": "spéit",
  "fr": "tard",
  "ph": "chpaït",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxfdc7a946",
  "lb": "gär",
  "fr": "volontiers",
  "ph": "guèr",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx2a9c27bf",
  "lb": "wäit",
  "fr": "loin",
  "ph": "vaït",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-sons",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxd2cb249e",
  "lb": "Waasser",
  "fr": "l'eau, le w se dit v",
  "ph": "va-ser",
  "tr": "Waasser, pense à water.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx906c0642",
  "lb": "vill",
  "fr": "beaucoup, le v se dit f",
  "ph": "fill",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxabb902f7",
  "lb": "Sonn",
  "fr": "le soleil, le s se dit z",
  "ph": "zonn",
  "tr": "Sonn, pense à sun.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxbd73d357",
  "lb": "jo",
  "fr": "oui, le j se dit y",
  "ph": "yo",
  "tr": "jo se dit yo. Yo, c'est oui.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx3943cbc0",
  "lb": "Schoul",
  "fr": "l'école, sch se dit ch",
  "ph": "choul",
  "tr": "Schoul, pense à school.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx880b52a8",
  "lb": "ech",
  "fr": "je, ch au fond de la gorge",
  "ph": "èkh",
  "tr": "le son final est le kh de l'arabe.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx2b4e2182",
  "lb": "Haus",
  "fr": "la maison, au se dit ao",
  "ph": "haous",
  "tr": "Haus, pense à house.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-lettres",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx0d612c12",
  "lb": "Auto",
  "fr": "A comme Auto",
  "ph": "aou-to",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx6799b6b4",
  "lb": "Buch",
  "fr": "B comme Buch, le livre",
  "ph": "boukh",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxc60266a8",
  "lb": "Computer",
  "fr": "C comme Computer",
  "ph": "kom-piou-ter",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxe134adc5",
  "lb": "Dag",
  "fr": "D comme Dag, le jour",
  "ph": "dakh",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx1f444844",
  "lb": "Ee",
  "fr": "E comme Ee, l'oeuf",
  "ph": "é",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx295be004",
  "lb": "Fra",
  "fr": "F comme Fra, la femme",
  "ph": "fra",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxe158e925",
  "lb": "gutt",
  "fr": "G comme gutt, bien",
  "ph": "gout",
  "tr": "gutt, pense à good.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx6f901581",
  "lb": "Iessen",
  "fr": "I comme Iessen, manger",
  "ph": "i-eu-seune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx14febe36",
  "lb": "Jong",
  "fr": "J comme Jong, le garçon",
  "ph": "yong",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx5da1ba24",
  "lb": "Kand",
  "fr": "K comme Kand, l'enfant",
  "ph": "kant",
  "tr": "Kand, pense à kid.",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx3d3b60b2",
  "lb": "Land",
  "fr": "L comme Land, le pays",
  "ph": "lant",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx85171451",
  "lb": "Mamm",
  "fr": "M comme Mamm, la mère",
  "ph": "mamm",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-1",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx4c08b0b7",
  "lb": "Nuecht",
  "fr": "N comme Nuecht, la nuit",
  "ph": "nou-eukht",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxb3fc0e1a",
  "lb": "Owend",
  "fr": "O comme Owend, le soir",
  "ph": "o-vent",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx0c20a48c",
  "lb": "Papp",
  "fr": "P comme Papp, le père",
  "ph": "papp",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxd501d3ec",
  "lb": "Quiz",
  "fr": "Q comme Quiz",
  "ph": "kviss",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx14205d78",
  "lb": "Rees",
  "fr": "R comme Rees, le voyage",
  "ph": "réss",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx6e0b66b5",
  "lb": "Stad",
  "fr": "S comme Stad, la ville",
  "ph": "chtat",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lxe4edfacb",
  "lb": "Telefon",
  "fr": "T comme Telefon",
  "ph": "té-lé-fon",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx1a7fe58c",
  "lb": "Auer",
  "fr": "U comme Auer, l'heure",
  "ph": "aou-er",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx7c342114",
  "lb": "Vugel",
  "fr": "V comme Vugel, l'oiseau",
  "ph": "fou-guel",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx8763f04e",
  "lb": "Wieder",
  "fr": "W comme Wieder, le temps",
  "ph": "vi-der",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx7beb6f3f",
  "lb": "Zäit",
  "fr": "Z comme Zäit, le temps qui passe",
  "ph": "tsaït",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "lx012b9f4a",
  "lb": "Äppel",
  "fr": "A tréma comme Äppel, les pommes",
  "ph": "è-pel",
  "tr": "Äppel, pense à apple.",
  "alt": [],
  "syl": 2,
  "paquet": "mi-alphabet-2",
  "niveau": 5,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "micro",
  "derive": false,
  "micro": true
 },
 {
  "id": "dv387042f2",
  "lb": "Wou ass d'Strooss?",
  "fr": "où est la rue?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx546466a6"
  ]
 },
 {
  "id": "dvea9a4749",
  "lb": "Wou ass d'Schoul?",
  "fr": "où est l'école?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx4cd48d1c"
  ]
 },
 {
  "id": "dv03343160",
  "lb": "Wou ass d'Haus?",
  "fr": "où est la maison?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx31476875"
  ]
 },
 {
  "id": "dve2e69518",
  "lb": "Wou ass den Zuch?",
  "fr": "où est le train?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx48c27e30"
  ]
 },
 {
  "id": "dv85b480e9",
  "lb": "Wou ass d'Aarbecht?",
  "fr": "où est le travail?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx3c881ec2"
  ]
 },
 {
  "id": "dvee091383",
  "lb": "Wou ass d'Sitzung?",
  "fr": "où est la réunion?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lxd5524d5f"
  ]
 },
 {
  "id": "dv354309ed",
  "lb": "Wou ass d'Grenz?",
  "fr": "où est la frontière?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx801c34ee"
  ]
 },
 {
  "id": "dvc4690d0b",
  "lb": "Wou ass d'Rechnung?",
  "fr": "où est l'addition?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx3bbcfc00"
  ]
 },
 {
  "id": "dv1f0b44ff",
  "lb": "Wou ass d'Nummer?",
  "fr": "où est le numéro?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lxd95d5dcf"
  ]
 },
 {
  "id": "dv895e6b96",
  "lb": "Wou ass d'Auer?",
  "fr": "où est l'heure?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lxc811ed14"
  ]
 },
 {
  "id": "dv0c24c4a4",
  "lb": "Wou ass de Chef?",
  "fr": "où est le chef?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx704df6d8"
  ]
 },
 {
  "id": "dv5d9ff585",
  "lb": "Wou ass de Kolleeg?",
  "fr": "où est le collègue?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx517f9ebe"
  ]
 },
 {
  "id": "dv313885cc",
  "lb": "Wou ass d'Equipe?",
  "fr": "où est l'équipe?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx4b6c0cb3"
  ]
 },
 {
  "id": "dv69f11a01",
  "lb": "Wou ass d'Grupp?",
  "fr": "où est le groupe?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx82248681"
  ]
 },
 {
  "id": "dvd27cec38",
  "lb": "Wou ass de Jong?",
  "fr": "où est le garçon?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx5d9375c7"
  ]
 },
 {
  "id": "dvf9bf432c",
  "lb": "Wou ass d'Meedchen?",
  "fr": "où est la fille?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lxf1578950"
  ]
 },
 {
  "id": "dvf7e4b545",
  "lb": "Wou ass d'Kand?",
  "fr": "où est l'enfant?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lxeb2ac6e8"
  ]
 },
 {
  "id": "dvdf6f9296",
  "lb": "Wou ass d'Fra?",
  "fr": "où est la femme?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx585c1ddc"
  ]
 },
 {
  "id": "dvd10c6886",
  "lb": "Wou ass de Mann?",
  "fr": "où est l'homme?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx4b6417d3"
  ]
 },
 {
  "id": "dv06bc69c9",
  "lb": "Wou ass den Auto?",
  "fr": "où est la voiture?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lx395e6e44"
  ]
 },
 {
  "id": "dv6bceaa5d",
  "lb": "Wou ass de Stau?",
  "fr": "où est l'embouteillage?",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": true,
  "de": [
   "lx3de1857c",
   "lxc4135816"
  ]
 },
 {
  "id": "dv14231745",
  "lb": "Dat ass schéin",
  "fr": "c'est beau",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lxc2894f6f",
   "lx5dab9888"
  ]
 },
 {
  "id": "dv08968149",
  "lb": "Dat ass wäit",
  "fr": "c'est loin",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lxc2894f6f",
   "lx2a9c27bf"
  ]
 },
 {
  "id": "dv0e1e0171",
  "lb": "Dat ass kal",
  "fr": "c'est froid",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lxc2894f6f",
   "lxe226448d"
  ]
 },
 {
  "id": "dvcff0ff5b",
  "lb": "Dat ass waarm",
  "fr": "c'est chaud",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lxc2894f6f",
   "lx3d6c9d1a"
  ]
 },
 {
  "id": "dv1881a781",
  "lb": "Et ass gutt",
  "fr": "c'est bien",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lxbbb62fb8",
   "lxe158e925"
  ]
 },
 {
  "id": "dv0ad94a94",
  "lb": "Et ass kloer",
  "fr": "c'est clair",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lxbbb62fb8",
   "lxe57ca2f2"
  ]
 },
 {
  "id": "dv7769ab0f",
  "lb": "Et ass schéin",
  "fr": "c'est beau",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lxbbb62fb8",
   "lx5dab9888"
  ]
 },
 {
  "id": "dv3ed82e63",
  "lb": "Et ass wäit",
  "fr": "c'est loin",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lxbbb62fb8",
   "lx2a9c27bf"
  ]
 },
 {
  "id": "dvccb5bac5",
  "lb": "Ech hätt gär e Waasser",
  "fr": "je voudrais une eau",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": true,
  "de": [
   "lx24528c27",
   "lxdffc232d"
  ]
 },
 {
  "id": "dvb1095030",
  "lb": "Bis Méindeg",
  "fr": "à lundi",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lx81af183e"
  ]
 },
 {
  "id": "dv163488b8",
  "lb": "Bis Dënschdeg",
  "fr": "à mardi",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lxf4543138"
  ]
 },
 {
  "id": "dv6ff4c9c8",
  "lb": "Bis Mëttwoch",
  "fr": "à mercredi",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lxc04639e3"
  ]
 },
 {
  "id": "dv221f06bd",
  "lb": "Bis Donneschdeg",
  "fr": "à jeudi",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lx533c3a71"
  ]
 },
 {
  "id": "dve2460a2d",
  "lb": "Bis Freideg",
  "fr": "à vendredi",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lx70107732"
  ]
 },
 {
  "id": "dvf7fea18e",
  "lb": "Bis Samschdeg",
  "fr": "à samedi",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lx71de5223"
  ]
 },
 {
  "id": "dv49d29f15",
  "lb": "Bis Sonndeg",
  "fr": "à dimanche",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx890519c9",
   "lx4fc63f09"
  ]
 },
 {
  "id": "dv5142d7a2",
  "lb": "Ech schaffen muer",
  "fr": "je travaille demain",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx39e26013",
   "lxc0ac3849"
  ]
 },
 {
  "id": "dvabd19f25",
  "lb": "Ech schaffen spéider",
  "fr": "je travaille plus tard",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx39e26013",
   "lxe016c63a"
  ]
 },
 {
  "id": "dv666fa23b",
  "lb": "Ech schaffen elo",
  "fr": "je travaille maintenant",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx39e26013",
   "lx1ba85a7d"
  ]
 },
 {
  "id": "dv5b164dfe",
  "lb": "Ech kommen haut",
  "fr": "je viens aujourd'hui",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx06eb715b",
   "lx450c6b6a"
  ]
 },
 {
  "id": "dv678c364d",
  "lb": "Ech kommen muer",
  "fr": "je viens demain",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx06eb715b",
   "lxc0ac3849"
  ]
 },
 {
  "id": "dvadc42624",
  "lb": "Ech kommen spéider",
  "fr": "je viens plus tard",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx06eb715b",
   "lxe016c63a"
  ]
 },
 {
  "id": "dv6794e2c6",
  "lb": "Ech kommen elo",
  "fr": "je viens maintenant",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": true,
  "de": [
   "lx06eb715b",
   "lx1ba85a7d"
  ]
 },
 {
  "id": "dv68f3db48",
  "lb": "Haut kommen ech",
  "fr": "aujourd'hui, je viens",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": true,
  "de": [
   "lx450c6b6a",
   "lxfcff9f2e"
  ]
 },
 {
  "id": "dv84ab4bee",
  "lb": "Haut verstinn ech",
  "fr": "aujourd'hui, je comprends",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": true,
  "de": [
   "lx450c6b6a",
   "lxb831d0e0"
  ]
 },
 {
  "id": "dvdf0c2cac",
  "lb": "Muer schaffen ech",
  "fr": "demain, je travaille",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": true,
  "de": [
   "lxc0ac3849",
   "lxac5d5a62"
  ]
 },
 {
  "id": "dv6fc5b2df",
  "lb": "Muer verstinn ech",
  "fr": "demain, je comprends",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": true,
  "de": [
   "lxc0ac3849",
   "lxb831d0e0"
  ]
 },
 {
  "id": "dvd2773abf",
  "lb": "Elo schaffen ech",
  "fr": "maintenant, je travaille",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": true,
  "de": [
   "lx1ba85a7d",
   "lxac5d5a62"
  ]
 },
 {
  "id": "dv1c6381ba",
  "lb": "Elo kommen ech",
  "fr": "maintenant, je viens",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": true,
  "de": [
   "lx1ba85a7d",
   "lxfcff9f2e"
  ]
 },
 {
  "id": "dv3d7c77e0",
  "lb": "Ech kommen aus Lëtzebuerg",
  "fr": "je viens de Luxembourg",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lx06eb715b",
   "lx8ee30f9c"
  ]
 },
 {
  "id": "dv3c2a0542",
  "lb": "Ech wunnen zu Lëtzebuerg",
  "fr": "j'habite à Luxembourg",
  "ph": "",
  "tr": "",
  "alt": [],
  "syl": null,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": true,
  "de": [
   "lxcac494ba",
   "lx8ee30f9c"
  ]
 }
];
