/* PHRASES · première moitié
   Fichier GÉNÉRÉ par scripts/build-content.mjs. Ne pas éditer à la main.
   Aucune phrase n'a été inventée. Voir docs/V6_CONTENT.md.
   Statut linguistique : toutes les entrées sont "unverified".
   Le passage en "verified" est un geste humain, dans l'onglet
   Vérification, avec la source. */

export const PHRASES_A = [
 {
  "id": "lx3657a808",
  "lb": "Moien",
  "fr": "bonjour, salut",
  "ph": "mo-ï-eune",
  "tr": "Moien contient moi. Moi j'arrive, je dis Moien.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx52ccfdbd",
  "lb": "Gudde Moien",
  "fr": "bonjour, le matin",
  "ph": "goud-de mo-ï-eune",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxb4d93a19",
  "lb": "Gudden Owend",
  "fr": "bonsoir",
  "ph": "goud-den o-vent",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxe0db9f02",
  "lb": "Gutt Nuecht",
  "fr": "bonne nuit",
  "ph": "gout nou-eukht",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx8313d08a",
  "lb": "Äddi",
  "fr": "au revoir",
  "ph": "è-di",
  "tr": "Äddi, comme adieu raccourci.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx890519c9",
  "lb": "Bis geschwënn",
  "fr": "à bientôt",
  "ph": "biss gue-chvenn",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxc0ac3849",
  "lb": "Bis muer",
  "fr": "à demain",
  "ph": "biss moue-er",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-saluer",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx9f98291e",
  "lb": "Merci",
  "fr": "merci",
  "ph": "mèr-si",
  "tr": "identique au français. Un cadeau.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-politesse",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxdfd18d59",
  "lb": "Villmools merci",
  "fr": "merci beaucoup",
  "ph": "fill-mols mèr-si",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-politesse",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx487f8ee4",
  "lb": "Wann ech gelift",
  "fr": "s'il vous plaît",
  "ph": "van èkh gue-lift",
  "tr": "mot à mot, quand cela me plaît.",
  "alt": [],
  "syl": 4,
  "paquet": "pk-politesse",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx5a1f15d4",
  "lb": "Entschëllegt",
  "fr": "excusez-moi",
  "ph": "ènt-chè-lekht",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-politesse",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx457999c0",
  "lb": "Kee Problem",
  "fr": "pas de problème",
  "ph": "ké pro-blém",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-politesse",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxa1deed7f",
  "lb": "Gär geschitt",
  "fr": "je vous en prie",
  "ph": "guèr gue-chitt",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-politesse",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx0354a22a",
  "lb": "Ech verstinn net",
  "fr": "je ne comprends pas",
  "ph": "èkh fèr-chtinn nét",
  "tr": "net à la fin, c'est la négation. Comme not.",
  "alt": [],
  "syl": 4,
  "paquet": "pk-secours",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx15918030",
  "lb": "Ech weess net",
  "fr": "je ne sais pas",
  "ph": "èkh véss nét",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-secours",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx1e42a8b0",
  "lb": "Méi lues, wann ech gelift",
  "fr": "plus lentement, s'il vous plaît",
  "ph": "maï lou-ess",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-secours",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lxaf353b6a",
  "lb": "Kënnt Dir dat widderhuelen?",
  "fr": "pouvez-vous répéter ?",
  "ph": "kennt dir dat vi-der-hou-leune",
  "tr": "",
  "alt": [],
  "syl": 7,
  "paquet": "pk-secours",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx8f842437",
  "lb": "Wat heescht dat?",
  "fr": "qu'est-ce que ça veut dire ?",
  "ph": "vat héchst dat",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-secours",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lxd22a9ae4",
  "lb": "Schwätzt Dir Franséisch?",
  "fr": "parlez-vous français ?",
  "ph": "chvètst dir fran-zaïch",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-secours",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx1a7150a0",
  "lb": "Nee",
  "fr": "non",
  "ph": "né",
  "tr": "Nee, un é long. Pense à négatif.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx1ca5eb98",
  "lb": "Vläicht",
  "fr": "peut-être",
  "ph": "flaïkht",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx75f595fa",
  "lb": "Sécher",
  "fr": "bien sûr",
  "ph": "zé-kher",
  "tr": "Sécher, pense à sûr.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxa6d83e36",
  "lb": "E bëssen",
  "fr": "un peu",
  "ph": "e bè-seune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxf7f49581",
  "lb": "Ganz",
  "fr": "très, tout à fait",
  "ph": "gants",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx7e879b0a",
  "lb": "Guer net",
  "fr": "pas du tout",
  "ph": "gouer nét",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-repondre",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx3bd3ab61",
  "lb": "Wéi geet et?",
  "fr": "comment ça va ?",
  "ph": "vaï guét ét",
  "tr": "geet ressemble à goes. Comment ça goes.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-cava",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx41a44911",
  "lb": "Et geet mir gutt",
  "fr": "je vais bien",
  "ph": "ét guét mir gout",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-cava",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx4f6515fa",
  "lb": "Ganz gutt, merci",
  "fr": "très bien, merci",
  "ph": "gants gout mèr-si",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-cava",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx129a847b",
  "lb": "An dir?",
  "fr": "et vous ?",
  "ph": "ann dir",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-cava",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxcfbab444",
  "lb": "Net esou gutt",
  "fr": "pas très bien",
  "ph": "nét é-zo gout",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-cava",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxd4a59311",
  "lb": "Ech si midd",
  "fr": "je suis fatigué",
  "ph": "èkh si mit",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-cava",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx983ba2bf",
  "lb": "Ech heeschen …",
  "fr": "je m'appelle …",
  "ph": "èkh hé-cheune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx098d7ddf",
  "lb": "Wéi heeschs du?",
  "fr": "comment tu t'appelles ?",
  "ph": "vaï héchs dou",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxa11021a8",
  "lb": "Wéi heescht Dir?",
  "fr": "comment vous appelez-vous ?",
  "ph": "vaï héchst dir",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx06eb715b",
  "lb": "Ech kommen aus Frankräich",
  "fr": "je viens de France",
  "ph": "èkh ko-meune aous frank-raïkh",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxcac494ba",
  "lb": "Ech wunnen zu …",
  "fr": "j'habite à …",
  "ph": "èkh vou-neune tsou",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lx39e26013",
  "lb": "Ech schaffen zu Lëtzebuerg",
  "fr": "je travaille au Luxembourg",
  "ph": "èkh cha-feune tsou",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxae5583eb",
  "lb": "Ech léieren Lëtzebuergesch",
  "fr": "j'apprends le luxembourgeois",
  "ph": "èkh laï-eureune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-presenter",
  "niveau": 1,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 5,
  "cat": "social",
  "derive": false
 },
 {
  "id": "lxf8e3f513",
  "lb": "Ech hätt gär e Kaffi",
  "fr": "je voudrais un café",
  "ph": "èkh hèt guèr e ka-fi",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxdffc232d",
  "lb": "E Waasser, wann ech gelift",
  "fr": "une eau, s'il vous plaît",
  "ph": "e va-ser",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lx3bbcfc00",
  "lb": "D'Rechnung, wann ech gelift",
  "fr": "l'addition, s'il vous plaît",
  "ph": "d'rèkh-noung",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lx8f5bf8b2",
  "lb": "Ech hunn Honger",
  "fr": "j'ai faim",
  "ph": "èkh hounn hong-er",
  "tr": "Honger, pense à hungry.",
  "alt": [],
  "syl": 4,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxdf6d33bb",
  "lb": "Ech hunn Duuscht",
  "fr": "j'ai soif",
  "ph": "èkh hounn douscht",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxa9a47d85",
  "lb": "Dat ass gutt",
  "fr": "c'est bon",
  "ph": "dat ass gout",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-commander",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lx24ad5a3e",
  "lb": "Wéivill?",
  "fr": "combien ?",
  "ph": "vaï-fill",
  "tr": "wéi, comment. vill, beaucoup. Comment beaucoup, donc combien.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lx953e2692",
  "lb": "Wat kascht dat?",
  "fr": "combien ça coûte ?",
  "ph": "vat kacht dat",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxa77f85b7",
  "lb": "zéng Euro",
  "fr": "dix euros",
  "ph": "tsèng eu-ro",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lx220eb3b9",
  "lb": "Wéi al bass du?",
  "fr": "quel âge as-tu ?",
  "ph": "vaï al bass dou",
  "tr": "al veut dire vieux. Comment vieux es-tu.",
  "alt": [],
  "syl": 4,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxd95d5dcf",
  "lb": "d'Nummer",
  "fr": "le numéro",
  "ph": "d'nou-mer",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxc811ed14",
  "lb": "d'Auer",
  "fr": "l'heure, la montre",
  "ph": "d'aou-er",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxd2ecf498",
  "lb": "Wéi spéit ass et?",
  "fr": "quelle heure est-il ?",
  "ph": "vaï chpaït ass ét",
  "tr": "spéit veut dire tard. Comment tard est-il.",
  "alt": [],
  "syl": 4,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lxbbb62fb8",
  "lb": "Et ass zéng Auer",
  "fr": "il est dix heures",
  "ph": "ét ass tsèng aou-er",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-prix-heure",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "commerce",
  "derive": false
 },
 {
  "id": "lx2fa4117c",
  "lb": "lénks",
  "fr": "à gauche",
  "ph": "lènks",
  "tr": "lénks commence par L, comme left.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx85e28a70",
  "lb": "riets",
  "fr": "à droite",
  "ph": "ri-ets",
  "tr": "riets commence par R, comme right.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx0aad6690",
  "lb": "riicht aus",
  "fr": "tout droit",
  "ph": "riikht aous",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx3de1857c",
  "lb": "Wou ass …?",
  "fr": "où est … ?",
  "ph": "vou ass",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx546466a6",
  "lb": "d'Strooss",
  "fr": "la rue",
  "ph": "d'chtrôss",
  "tr": "Strooss, pense à street.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lxc4135816",
  "lb": "de Stau",
  "fr": "l'embouteillage",
  "ph": "de chtaou",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx801c34ee",
  "lb": "d'Grenz",
  "fr": "la frontière",
  "ph": "d'grènts",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx48c27e30",
  "lb": "den Zuch",
  "fr": "le train",
  "ph": "den tsoukh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-chemin",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "deplacer",
  "derive": false
 },
 {
  "id": "lx31476875",
  "lb": "d'Haus",
  "fr": "la maison",
  "ph": "d'haous",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx37c6cd89",
  "lb": "doheem",
  "fr": "à la maison",
  "ph": "do-hém",
  "tr": "doheem, pense à home.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lxbb63e08b",
  "lb": "d'Wieder",
  "fr": "le temps qu'il fait",
  "ph": "d'vi-der",
  "tr": "Wieder, pense à weather.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx82ead77a",
  "lb": "Et reent",
  "fr": "il pleut",
  "ph": "ét rént",
  "tr": "reent, pense à rain.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lxe226448d",
  "lb": "Et ass kal",
  "fr": "il fait froid",
  "ph": "ét ass kal",
  "tr": "kal, pense à cold.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx3d6c9d1a",
  "lb": "Et ass waarm",
  "fr": "il fait chaud",
  "ph": "ét ass varm",
  "tr": "waarm, pense à warm.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx7a5048c8",
  "lb": "D'Sonn schéngt",
  "fr": "le soleil brille",
  "ph": "d'zonn chèngt",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-meteo",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx46424bd8",
  "lb": "haut",
  "fr": "aujourd'hui",
  "ph": "haout",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx18676f74",
  "lb": "muer",
  "fr": "demain",
  "ph": "moue-er",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lxcd798c45",
  "lb": "elo",
  "fr": "maintenant",
  "ph": "é-lo",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lxe016c63a",
  "lb": "spéider",
  "fr": "plus tard",
  "ph": "chpaï-der",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx3ce4731c",
  "lb": "de Moien",
  "fr": "le matin",
  "ph": "de mo-ï-eune",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx7937c6da",
  "lb": "den Owend",
  "fr": "le soir",
  "ph": "den o-vent",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx7a11401a",
  "lb": "de Weekend",
  "fr": "le week-end",
  "ph": "de ouik-end",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-quand",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx81af183e",
  "lb": "Méindeg",
  "fr": "lundi",
  "ph": "maïn-dekh",
  "tr": "Méindeg, pense à Monday, la lune.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lxf4543138",
  "lb": "Dënschdeg",
  "fr": "mardi",
  "ph": "dench-dekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lxc04639e3",
  "lb": "Mëttwoch",
  "fr": "mercredi",
  "ph": "mèt-vokh",
  "tr": "Mëttwoch, le milieu de la semaine.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx533c3a71",
  "lb": "Donneschdeg",
  "fr": "jeudi",
  "ph": "do-nech-dekh",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx70107732",
  "lb": "Freideg",
  "fr": "vendredi",
  "ph": "fraï-dekh",
  "tr": "Freideg, pense à Friday.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx71de5223",
  "lb": "Samschdeg",
  "fr": "samedi",
  "ph": "zamch-dekh",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx4fc63f09",
  "lb": "Sonndeg",
  "fr": "dimanche",
  "ph": "zon-dekh",
  "tr": "Sonndeg, le jour du soleil, Sonn.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx3f8f7790",
  "lb": "d'Woch",
  "fr": "la semaine",
  "ph": "d'vokh",
  "tr": "Woch, pense à week.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-jours",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "quotidien",
  "derive": false
 },
 {
  "id": "lx6da0ea8a",
  "lb": "wien",
  "fr": "qui",
  "ph": "vi-eune",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lxa3bbe1a8",
  "lb": "wat",
  "fr": "quoi",
  "ph": "vat",
  "tr": "wat, pense à what.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx6054199e",
  "lb": "wou",
  "fr": "où",
  "ph": "vou",
  "tr": "wou, pense à where.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx4ecbb359",
  "lb": "wéini",
  "fr": "quand",
  "ph": "vaï-ni",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lxd9dc5bb3",
  "lb": "firwat",
  "fr": "pourquoi",
  "ph": "fir-vat",
  "tr": "fir-wat, pour quoi. Comme en français.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lxb1378b18",
  "lb": "wéi",
  "fr": "comment",
  "ph": "vaï",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx778a68fd",
  "lb": "Wat ass dat?",
  "fr": "qu'est-ce que c'est ?",
  "ph": "vat ass dat",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-questions",
  "niveau": 2,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "secours",
  "derive": false
 },
 {
  "id": "lx70f92ac7",
  "lb": "ech sinn",
  "fr": "je suis",
  "ph": "èkh zinn",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx48c14b07",
  "lb": "ech hunn",
  "fr": "j'ai",
  "ph": "èkh hounn",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx324d9210",
  "lb": "ech goen",
  "fr": "je vais",
  "ph": "èkh gô-eune",
  "tr": "goen, pense à go.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx0233ebbf",
  "lb": "ech kommen",
  "fr": "je viens",
  "ph": "èkh ko-meune",
  "tr": "kommen, pense à come.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx6774e060",
  "lb": "ech schaffen",
  "fr": "je travaille",
  "ph": "èkh cha-feune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx5a0a45eb",
  "lb": "ech schwätzen",
  "fr": "je parle",
  "ph": "èkh chvèt-seune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx12009a42",
  "lb": "ech verstinn",
  "fr": "je comprends",
  "ph": "èkh fèr-chtinn",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx82e1cac1",
  "lb": "ech maachen",
  "fr": "je fais",
  "ph": "èkh ma-kheune",
  "tr": "maachen, pense à make.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxd6fde8d0",
  "lb": "ech gesinn",
  "fr": "je vois",
  "ph": "èkh gue-zinn",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxde78bc0d",
  "lb": "ech héieren",
  "fr": "j'entends",
  "ph": "èkh haï-eureune",
  "tr": "héieren, pense à hear.",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-ech",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxa1edaa04",
  "lb": "du schaffs",
  "fr": "tu travailles",
  "ph": "dou chafs",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx16724518",
  "lb": "hie schafft",
  "fr": "il travaille",
  "ph": "hi chafft",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx4e4af1a3",
  "lb": "si schafft",
  "fr": "elle travaille",
  "ph": "zi chafft",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxceb66548",
  "lb": "du bass",
  "fr": "tu es",
  "ph": "dou bass",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxae102626",
  "lb": "hien ass",
  "fr": "il est",
  "ph": "hi-eune ass",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx487125ef",
  "lb": "du hues",
  "fr": "tu as",
  "ph": "dou hou-ess",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxecfe81d4",
  "lb": "hien huet",
  "fr": "il a",
  "ph": "hi-eune hou-eut",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx302ad483",
  "lb": "mir schaffen",
  "fr": "nous travaillons",
  "ph": "mir cha-feune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxf9fdbbfd",
  "lb": "dir schafft",
  "fr": "vous travaillez",
  "ph": "dir chafft",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx64beb091",
  "lb": "si schaffen",
  "fr": "ils travaillent",
  "ph": "zi cha-feune",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx380c2bc3",
  "lb": "mir sinn",
  "fr": "nous sommes",
  "ph": "mir zinn",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx54b17457",
  "lb": "mir hunn",
  "fr": "nous avons",
  "ph": "mir hounn",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx4ba91cdd",
  "lb": "Dir sidd",
  "fr": "vous êtes",
  "ph": "dir zitt",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-verbes-autres",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx450c6b6a",
  "lb": "Ech schaffen net haut",
  "fr": "je ne travaille pas aujourd'hui",
  "ph": "èkh cha-feune nét haout",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-negation",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxa6e39547",
  "lb": "Ech hunn keng Zäit",
  "fr": "je n'ai pas le temps",
  "ph": "èkh hounn kèng tsaït",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-negation",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxc2894f6f",
  "lb": "Dat ass net gutt",
  "fr": "ce n'est pas bon",
  "ph": "dat ass nét gout",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-negation",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxca21e2fc",
  "lb": "Ech kann net",
  "fr": "je ne peux pas",
  "ph": "èkh kann nét",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-negation",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx75275a77",
  "lb": "Nach net",
  "fr": "pas encore",
  "ph": "nakh nét",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-negation",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx4d498f36",
  "lb": "Näischt",
  "fr": "rien",
  "ph": "naïcht",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-negation",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx2c9f4aa4",
  "lb": "ech kann",
  "fr": "je peux",
  "ph": "èkh kann",
  "tr": "kann, pense à can.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-modaux",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx753f5c17",
  "lb": "ech muss",
  "fr": "je dois",
  "ph": "èkh mouss",
  "tr": "muss, pense à must.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-modaux",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx979a4c13",
  "lb": "ech well",
  "fr": "je veux",
  "ph": "èkh vèll",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-modaux",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx24528c27",
  "lb": "ech hätt gär",
  "fr": "je voudrais",
  "ph": "èkh hèt guèr",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-modaux",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx1ba85a7d",
  "lb": "Ech muss elo goen",
  "fr": "je dois y aller maintenant",
  "ph": "èkh mouss é-lo gô-eune",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-modaux",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx224ff805",
  "lb": "Kanns du mir hëllefen?",
  "fr": "peux-tu m'aider ?",
  "ph": "kanns dou mir hè-le-feune",
  "tr": "hëllefen, pense à help.",
  "alt": [],
  "syl": 6,
  "paquet": "pk-modaux",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxac5d5a62",
  "lb": "Haut schaffen ech",
  "fr": "aujourd'hui, je travaille",
  "ph": "haout cha-feune èkh",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxfcff9f2e",
  "lb": "Muer kommen ech",
  "fr": "demain, je viens",
  "ph": "moue-er ko-meune èkh",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxb831d0e0",
  "lb": "Elo verstinn ech",
  "fr": "maintenant, je comprends",
  "ph": "é-lo fèr-chtinn èkh",
  "tr": "",
  "alt": [],
  "syl": 5,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx02cb634d",
  "lb": "Am Auto léieren ech",
  "fr": "dans la voiture, j'apprends",
  "ph": "am aou-to laï-eureune èkh",
  "tr": "",
  "alt": [],
  "syl": 6,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx122f0494",
  "lb": "Ech schaffen haut",
  "fr": "je travaille aujourd'hui",
  "ph": "èkh cha-feune haout",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-ordre",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx4b6417d3",
  "lb": "de Mann",
  "fr": "l'homme",
  "ph": "de mann",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx585c1ddc",
  "lb": "d'Fra",
  "fr": "la femme",
  "ph": "d'fra",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxeb2ac6e8",
  "lb": "d'Kand",
  "fr": "l'enfant",
  "ph": "d'kant",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx395e6e44",
  "lb": "den Auto",
  "fr": "la voiture",
  "ph": "den aou-to",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx72200743",
  "lb": "eng Fra",
  "fr": "une femme",
  "ph": "eng fra",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx9ac45dfd",
  "lb": "e Mann",
  "fr": "un homme",
  "ph": "e mann",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lxed9c7fc3",
  "lb": "d'Kanner",
  "fr": "les enfants",
  "ph": "d'ka-ner",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-articles",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 2,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx20e1ab6f",
  "lb": "Ech hunn geschafft",
  "fr": "j'ai travaillé",
  "ph": "èkh hounn gue-chafft",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-passe",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx97b3b4ea",
  "lb": "Ech hunn geschwat",
  "fr": "j'ai parlé",
  "ph": "èkh hounn gue-chvat",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-passe",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx4da94058",
  "lb": "Ech si gaangen",
  "fr": "je suis allé",
  "ph": "èkh si gang-eune",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-passe",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx1f230b8a",
  "lb": "Ech si komm",
  "fr": "je suis venu",
  "ph": "èkh si komm",
  "tr": "",
  "alt": [],
  "syl": 3,
  "paquet": "pk-passe",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx6ab3ffe4",
  "lb": "Gëschter hunn ech geschafft",
  "fr": "hier, j'ai travaillé",
  "ph": "guèch-ter hounn èkh",
  "tr": "",
  "alt": [],
  "syl": 4,
  "paquet": "pk-passe",
  "niveau": 3,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 3,
  "cat": "structure",
  "derive": false
 },
 {
  "id": "lx3438df5f",
  "lb": "awer",
  "fr": "mais",
  "ph": "a-ver",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lxbd848328",
  "lb": "well",
  "fr": "parce que",
  "ph": "vèll",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx09706c41",
  "lb": "also",
  "fr": "donc, alors",
  "ph": "al-zo",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx2cd3eb82",
  "lb": "dann",
  "fr": "alors",
  "ph": "dann",
  "tr": "dann, pense à then.",
  "alt": [],
  "syl": 1,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx29eafa3c",
  "lb": "och",
  "fr": "aussi",
  "ph": "okh",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx14442c36",
  "lb": "nëmmen",
  "fr": "seulement",
  "ph": "nè-meune",
  "tr": "",
  "alt": [],
  "syl": 2,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx1357b70d",
  "lb": "schonn",
  "fr": "déjà",
  "ph": "chonn",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lx852cb848",
  "lb": "nach",
  "fr": "encore",
  "ph": "nakh",
  "tr": "",
  "alt": [],
  "syl": 1,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 },
 {
  "id": "lxe9c6b83d",
  "lb": "ëmmer",
  "fr": "toujours",
  "ph": "è-mer",
  "tr": "ëmmer, pense à immersion. Toujours dedans.",
  "alt": [],
  "syl": 2,
  "paquet": "pk-connecteurs",
  "niveau": 4,
  "st": "unverified",
  "src": "",
  "ver": "",
  "audio": null,
  "util": 4,
  "cat": "ecoute",
  "derive": false
 }
];
